### ISSUE TITLE
 AttributeError: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by Rohit-Satyam** [TRON-Bioinformatics/covigator-ngs-pipeline#32]
**Describe the bug**
Getting error at Pangolin Step. I made a completely new environment and still getting this error.

```
Error executing process > 'PANGOLIN_LINEAGE (23_S2)'

Caused by:
  Process `PANGOLIN_LINEAGE (23_S2)` terminated with an error exit status (1)

Command executed:

  mkdir tmp
  
  #--decompress-model
  pangolin     23_S2.lofreq.fasta     --outfile 23_S2.lofreq.pangolin.csv     --tempdir ./tmp     --threads 1

Command exit status:
  1

Command output:
  All dependencies satisfied.
  The query file is:23_S2.lofreq.fasta
  ** Running sequence QC **
  Number of sequences detected: 1
  Total passing QC: 1
  
  Data files found:
  Trained model:	/home/subudhak/Documents/COVID_Project/nextCov/covigator/work/conda/env-5845bf8b576de5c186debf2a42754a48/lib/python3.8/site-packages/pangoLEARN/data/decisionTree_v1.joblib
  Header file:	/home/subudhak/Documents/COVID_Project/nextCov/covigator/work/conda/env-5845bf8b576de5c186debf2a42754a48/lib/python3.8/site-packages/pangoLEARN/data/decisionTreeHeaders_v1.joblib
  Designated hash:	/home/subudhak/Documents/COVID_Project/nextCov/covigator/work/conda/env-5845bf8b576de5c186debf2a42754a48/lib/python3.8/site-packages/pangoLEARN/data/lineages.hash.csv

Command error:
  Traceback (most recent call last):
    File "/home/subudhak/Documents/COVID_Project/nextCov/covigator/work/conda/env-5845bf8b576de5c186debf2a42754a48/lib/python3.8/site-packages/snakemake/__init__.py", line 699, in snakemake
      success = workflow.execute(
    File "/home/subudhak/Documents/COVID_Project/nextCov/covigator/work/conda/env-5845bf8b576de5c186debf2a42754a48/lib/python3.8/site-packages/snakemake/workflow.py", line 1043, in execute
      logger.run_info("\n".join(dag.stats()))
    File "/home/subudhak/Documents/COVID_Project/nextCov/covigator/work/conda/env-5845bf8b576de5c186debf2a42754a48/lib/python3.8/site-packages/snakemake/dag.py", line 2176, in stats
      yield tabulate(rows, headers="keys")
    File "/home/subudhak/Documents/COVID_Project/nextCov/covigator/work/conda/env-5845bf8b576de5c186debf2a42754a48/lib/python3.8/site-packages/tabulate/__init__.py", line 2048, in tabulate
      list_of_lists, headers = _normalize_tabular_data(
    File "/home/subudhak/Documents/COVID_Project/nextCov/covigator/work/conda/env-5845bf8b576de5c186debf2a42754a48/lib/python3.8/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data
      rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
    File "/home/subudhak/Documents/COVID_Project/nextCov/covigator/work/conda/env-5845bf8b576de5c186debf2a42754a48/lib/python3.8/site-packages/tabulate/__init__.py", line 1471, in <lambda>
      rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
    File "/home/subudhak/Documents/COVID_Project/nextCov/covigator/work/conda/env-5845bf8b576de5c186debf2a42754a48/lib/python3.8/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
      (len(row) >= 1 and row[0] == SEPARATING_LINE)
    File "/home/subudhak/Documents/COVID_Project/nextCov/covigator/work/conda/env-5845bf8b576de5c186debf2a42754a48/lib/python3.8/site-packages/snakemake/rules.py", line 1127, in __eq__
      return self.name == other.name and self.output == other.output
  AttributeError: 'str' object has no attribute 'name'

Work dir:
  /home/subudhak/Documents/COVID_Project/nextCov/covigator/work/4e/0ebd32d5b6dc9c09cfaaa8ab782283

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`


```

**To Reproduce**

```
nextflow run tron-bioinformatics/covigator-ngs-pipeline [-r v0.13.0] -profile conda --fastq1 dana_covid_data/23_S23_L001_R1_001.fastq.gz --fastq2 dana_covid_data/23_S23_L001_R2_001.fastq.gz --name 23_S2 --output S2_23_results --primers ~/Documents/COVID_Project/nextCov/resources/primers.bed --keep_intermediate -resume
```

**Comment by priesgo** [comment]
you should be able to find a fasta file in `/home/subudhak/Documents/COVID_Project/nextCov/covigator/work/4e/0ebd32d5b6dc9c09cfaaa8ab782283`, could you share that? Also, please paste the content of `.command.sh`

**Comment by Rohit-Satyam** [comment]
Sorry for late reply

Here are the contents of `.command.sh`

```
#!/bin/bash -euo pipefail
mkdir tmp

#--decompress-model
pangolin     23_S2.lofreq.fasta     --outfile 23_S2.lofreq.pangolin.csv     --tempdir ./tmp     --threads 1
```

**Comment by priesgo** [comment]
Could you share the fasta?

**Comment by priesgo** [comment]
@Rohit-Satyam without the fasta sequence I cannot reproduce the error to understand what is happening there.

**Comment by priesgo** [comment]
I am closing this due to inactivity, feel free to reopen @Rohit-Satyam .
